
create table books
(
    book_id        int8 generated by default as identity,
    book_name      varchar(255) not null,
    book_price     float4 not null,
    book_quantity  int4,
    book_warehouse varchar(255) not null,
    primary key (book_id)
);

create table customers
(
    customer_id       int8 generated by default as identity,
    customer_discount float4,
    customer_district varchar(255) not null,
    customer_surname  varchar(255) not null,
    primary key (customer_id)
);

create table purchases
(
    purchase_id    int8 generated by default as identity,
    order_amount   float4 not null,
    order_date     timestamp not null,
    order_quantity int4 not null,
    book_id        int8 not null,
    customer_id    int8 not null,
    shop_id        int8 not null,
    primary key (purchase_id)
);

create table shops
(
    shop_id       int8 generated by default as identity,
    shop_discount float4,
    shop_district varchar(255) not null,
    shop_name     varchar(255) not null,
    primary key (shop_id)
);

alter table if exists purchases
    add constraint purchase_book_fk
    foreign key (book_id) references books;

alter table if exists purchases
    add constraint purchase_customer_fk
    foreign key (customer_id) references customers;

alter table if exists purchases
    add constraint purchase_shop_fk
    foreign key (shop_id) references shops;